from tkinter import *
window = Tk()
window.title("Sign Up / Sign In")
window.attributes('-fullscreen', True)
'''window.geometry("500x500")
window.resizable(0,0)'''
window.config(background="lightgreen")
l1=Label(window, text="Hubnet Registration Form", bg="lightgreen", fg="red", font=("algerian", 20, "bold"))
l1.pack(pady=10)
l2=Label(window, text="Enter User Name", bg="lightgreen", fg="red", font=("monotype corsiva", 17, "bold"))
l2.place(x=50, y=70)
e1=Entry(window, font=("monotype corsiva", 18, "bold"), bg="white", fg="blue", bd=10, width=32)
e1.place(x=50, y=100)
l3=Label(window, text="Enter Email ID", bg="lightgreen", fg="red", font=("monotype corsiva", 17, "bold"))
l3.place(x=50, y=170)
e2=Entry(window, font=("monotype corsiva", 18, "bold"), bg="white", fg="blue", bd=10, width=32)
e2.place(x=50, y=200)
l4=Label(window, text="Enter Password", bg="lightgreen", fg="red", font=("monotype corsiva", 17, "bold"))
l4.place(x=50, y=270)
e3=Entry(window, font=("monotype corsiva", 18, "bold"), bg="white", fg="red", bd=10, width=32)
e3.place(x=50, y=300)
c1=Checkbutton(window, text="All terms and conditions are accepted", bg="lightgreen", fg="red", font=("monotype corsiva", 18, "bold"))
c1.place(x=50, y=370)
b1=Button(window, text="Sign Up", bd=10, bg="lightgreen",fg="red", font=("monotype corsiva", 17, "bold"))
b1.place(x=50, y=420)
b2=Button(window, text="Sign In", bd=10, bg="lightgreen",fg="red", font=("monotype corsiva", 17, "bold"))
b2.place(x=175, y=420)
b3=Button(window, text="Reset Password", bd=10, bg="lightgreen",fg="red", font=("monotype corsiva", 17, "bold"))
b3.place(x=300, y=420)



window.mainloop()
